server.port: 7000
server.error.include-message: always


app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003


---
spring.config.activate.on-profile: docker

server.port: 8080

app:
  product-service:
    host: my-product-service
    port: 8080

  recommendation-service:
    host: my-recommendation-service
    port: 8080

  review-service:
    host: my-review-service
    port: 8080 
